version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: Excelsior2008
      POSTGRES_DB: todo_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todolist -d todo_app"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=todolist
      - DB_PASSWORD=Excelsior2008
      - DB_NAME=todo_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: